version: '3.8'
services:
  sushi-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sushi-sql-server
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD:-SushiPOS2026!}
      - MSSQL_PID=Developer
    volumes:
      - sushi_data:/var/opt/mssql

volumes:
  sushi_data: